In [13]:
import numpy as np
import time

In [2]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [17]:
#comparing execution performance
size=100_000_000

#pylist
py_list=list(range(size)) #[0,1,2,...size-1]
start=time.time()
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"py list time = {end-start}")

#numpy 
np_arr=np.array(py_list)
start=time.time()
sq_arr=np_arr**2 #vectorization
end=time.time()
print(f"np array time = {end-start}")

py list time = 22.889201402664185
np array time = 1.037052869796753


In [19]:
#memory 
import sys
print(f"py list size = {sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"numpy arr size = {np_arr.nbytes} bytes")

py list size = 80000005600000000 bytes
numpy arr size = 800000000 bytes


In [23]:
#create numpy arrays - using lists
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4,"sagarika"]) # all items will be converted to strings (homogenous data)
print(arr1)
print(arr2)
#finding data type
print(arr1.dtype)
print(arr2.dtype)
#shape - dimensions
print(arr1.shape)
print(arr2.shape)
#2D arrays
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(arr2D.shape)

[1 2 3 4]
['1' '2' '3' '4' 'sagarika']
int64
<U21
(4,)
(5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
